export const PROJECT = {
  PROJECT_REQUEST: "PROJECT_REQUEST",
  PROJECT_SUCCESS: "PROJECT_SUCCESS",
  PROJECT_FAIL: "PROJECT_FAIL",

  PROJECT_CREATE_REQUEST: "PROJECT_CREATE_REQUEST",
  PROJECT_CREATE_SUCCESS: "PROJECT_CREATE_SUCCESS",
  PROJECT_CREATE_FAIL: "PROJECT_CREATE_FAIL",

  PROJECT_EDITING_REQUEST: "PROJECT_EDITING_REQUEST",
  PROJECT_EDITING_SUCCESS: "PROJECT_EDITING_SUCCESS",
  PROJECT_EDITING_FAIL: "PROJECT_EDITING_FAIL",

  PROJECT_DELETE_REQUEST: "PROJECT_DELETE_REQUEST",
  PROJECT_DELETE_SUCCESS: "PROJECT_DELETE_SUCCESS",
  PROJECT_DELETE_FAIL: "PROJECT_DELETE_FAILURE",
};
