export const TASK = {
  TASK_REQUEST: "TASK_REQUEST",
  TASK_SUCCESS: "TASK_SUCCESS",
  TASK_FAIL: "TASK_FAIL",

  TASK_CREATE_REQUEST: "TASK_CREATE_REQUEST",
  TASK_CREATE_SUCCESS: "TASK_CREATE_SUCCESS",
  TASK_CREATE_FAIL: "TASK_CREATE_FAIL",

  TASK_UPDATE_REQUEST: "TASK_UPDATE_REQUEST",
  TASK_UPDATE_SUCCESS: "TASK_UPDATE_SUCCESS",
  TASK_UPDATE_FAIL: "TASK_UPDATE_FAIL",

  TASK_DELETE_REQUEST: "TASK_DELETE_REQUEST",
  TASK_DELETE_SUCCESS: "TASK_DELETE_SUCCESS",
  TASK_DELETE_FAIL: "TASK_DELETE_FAIL",
};
